scimilarity_brain_tissues = [
 'brain',
 'cerebrospinal fluid',
 'spinal cord',
 'cerebral hemisphere',
 'dorsal root ganglion',
 'occipital cortex',
 'central nervous system',
 'Brodmann (1909) area 9',
 'cerebellum',
 'choroid plexus',
 'cortex',
 'entorhinal cortex',
 'hypothalamus',
 'midbrain',
 'prefrontal cortex',
 'striatum',
 'superior frontal gyrus',
 'dorsolateral prefrontal cortex',
 'putamen',
 'middle temporal gyrus',
 'frontal cortex',
 'substantia nigra',
 'brain white matter',
 'temporal cortex',
 'primary visual cortex',
 'primary somatosensory cortex',
]

scimilarity_brain_cts = [
    "astrocyte",
    'microglial cell',
    'glial cell',
    'oligodendrocyte',
    'oligodendrocyte precursor cell',
    'radial glial cell'
]

tissue_to_organ = {
    'adipose tissue':'adipose',
    'subcutaneous adipose tissue':'adipose',
    'visceral fat':'adipose',
    'white adipose tissue':'adipose',
    
    'adrenal gland':'adrenal',
    
    'bronchus':'airway',
    'nasal cavity':'airway',
    'nasopharynx':'airway',
    'olfactory epithelium':'airway',
    'bronchiole':'airway',
    'respiratory airway':'airway', 
    'respiratory tract epithelium':'airway', 
    'trachea;bronchus':'airway',
    'trachea;respiratory airway':'airway',
    'trachea':'airway',
    'bronchial epithelial cell':'airway',
    'nose':'airway',
    
    'blood':'blood',
    
    'bone':'bone',
    'head_of_femur':'bone',
    'inferior nasal concha':'bone',
    'nasal turbinal':'bone',  
    'bone marrow':'bone marrow',
    'breast':'breast', 
    'mammary gland':'breast', 

    'portion of cartilage tissue in tibia':'cartilage',
    'cartilage tissue':'cartilage', 

    'tympanic membrane':'ear',  
    'epididymis epithelium':'epididymis',
    
    'fallopian tube':'fallopian tube',
    'fimbria of uterine tube':'fallopian tube',
    'isthmus of fallopian tube':'fallopian tube', 
    'ampulla of uterine tube':'fallopian tube',
    
    'ascending colon':'gut',
    'caecum':'gut',
    'colon':'gut',
    'colonic mucosa':'gut',
    'digestive tract':'gut',
    'epithelium of esophagus':'gut',
    'ileum':'gut',
    'descending colon':'gut', 
    'intestine':'gut',
    'mucosa':'gut', 'mucosa of descending colon':'gut',
    'mucosa of gallbladder':'gut', 
    'sigmoid colon':'gut', 
    'stomach':'gut', 
    'rectum':'gut',
    'transverse colon':'gut',
    'small intestine':'gut', 
    'large intestine':'gut', 
    'esophagus muscularis mucosa':'gut',

    'heart':'heart',
    'apex of heart': 'heart',
    'cardiac muscle of left ventricle':'heart',
    'heart left ventricle':'heart', 
    'heart right ventricle':'heart', 
    'left cardiac atrium':'heart',
    'interventricular septum':'heart', 
    'right cardiac atrium': 'heart', 
    'cardiac ventricle': 'heart',
    
    'kidney':'kidney',
    'cortex of kidney':'kidney',
    'outer cortex of kidney':'kidney', 
    'renal medulla':'kidney', 
    'renal papilla':'kidney',
    'inner medulla of kidney':'kidney', 
    'renal pelvis':'kidney',
    'kidney blood vessel':'kidney',

    'bile duct':'liver',
    'caudate lobe of liver':'liver',
    'liver':'liver',
    'right lobe of liver':'liver', 
    'left lobe of liver':'liver', 

    'left lung':'lung',
    'lower lobe of left lung':'lung', 
    'lower lobe of right lung':'lung', 
    'lung':'lung',
    'lung parenchyma':'lung', 
    'upper lobe of lung':'lung',
    'upper lobe of right lung':'lung',
    'lower lobe of lung':'lung',
    'upper lobe of left lung':'lung', 
    'lingula of left lung':'lung',
    'alveolar system':'lung', 
    
    'lymph node':'lymph node', 
    'mesenteric lymph node':'lymph node',
    'thoracic lymph node':'lymph node',
    'craniocervical lymph node':'lymph node', 
    'axillary lymph node':'lymph node',

    'gingiva':'mouth',
    'periodontium':'mouth',
    'dental pulp':'mouth',
    
    'muscle tissue':'muscle', 
    'gastrocnemius':'muscle', 
    'psoas muscle':'muscle', 

    'ovary':'ovary',
    'tertiary ovarian follicle':'ovary',
    
    'exocrine pancreas':'pancreas',
    'pancreas':'pancreas',
    'islet of Langerhans':'pancreas', 
    
    'omental fat pad':'peritoneum', 
    'peritoneum':'peritoneum', 
    'omentum':'peritoneum',

    'prostate gland':'prostate',
    'peripheral zone of prostate':'prostate', 
    'transition zone of prostate;urethra':'prostate',
    'transition zone of prostate':'prostate', 

    'spleen':'spleen', 
    'synovial fluid':'synovial joint',
    'synovial membrane of synovial joint':'synovial joint',
    'layer of synovial tissue':'synovial joint',

    'testis':'testis',
    'thymus':'thymus', 
    'tonsil':'tonsil', 

    'uterus':'uterus', 
    'urine':'urinary',
    'urothelium':'urinary',
    'urinary bladder':'urinary', 
    'ureter':'urinary',
    
    'aorta': 'vasculature',
    'vasculature': 'vasculature',
    'carotid artery segment': 'vasculature',
    'posterior vena cava': 'vasculature', 
    'mesenteric artery': 'vasculature', 
        }